# Generated by Django 5.2.8 on 2026-04-05 08:48

from django.db import migrations

def seed_data(apps, schema_editor):
    Destination = apps.get_model('destinations', 'Destination')
    Hotel = apps.get_model('destinations', 'Hotel')

    # Seed Destinations (Manually adding slugs because save() override doesn't run in migrations)
    dest1 = Destination.objects.create(
        name='Paris, France',
        slug='paris-france',
        city='Paris',
        country='France',
        description='The city of lights, known for the Eiffel Tower, Louvre museum, and romantic atmosphere.',
        category='city',
        base_price=12000.00,
        is_featured=True,
        avg_rating=4.8
    )

    dest2 = Destination.objects.create(
        name='Goa, India',
        slug='goa-india',
        city='Goa',
        country='India',
        description='Famous for its beaches, night life, and historic architecture. A paradise for beach lovers.',
        category='beach',
        base_price=5000.00,
        is_featured=True,
        avg_rating=4.5
    )

    dest3 = Destination.objects.create(
        name='Manali, India',
        slug='manali-india',
        city='Manali',
        country='India',
        description='A high-altitude Himalayan resort town known as a honeymoon destination and backpacking hub.',
        category='mountain',
        base_price=3500.00,
        is_featured=False,
        avg_rating=4.2
    )

    # Seed Hotels
    Hotel.objects.create(
        destination=dest1,
        name='Eiffel View Luxury',
        description='A premium hotel overlooking the Eiffel Tower with first-class amenities.',
        address='7th Arrondissement, Paris',
        price_per_night=15000.00,
        star_rating=5,
        amenities=['WiFi', 'Pool', 'Breakfast', 'Gym']
    )

    Hotel.objects.create(
        destination=dest2,
        name='Sun & Sand Resort',
        description='A beautiful resort right on Calangute beach with amazing sea views.',
        address='Calangute Beach, Goa',
        price_per_night=6000.00,
        star_rating=4,
        amenities=['WiFi', 'Bar', 'Beach Access']
    )

    Hotel.objects.create(
        destination=dest3,
        name='Himalayan Retreat',
        description='Cozy stay in the mountains with a perfect view of the snow-capped peaks.',
        address='Old Manali, Himachal Pradesh',
        price_per_night=3000.00,
        star_rating=4,
        amenities=['WiFi', 'Heater', 'Trekking Desk']
    )

class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_base_price'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
