# Generated by Django 5.2.8 on 2026-04-05 08:40

from django.db import migrations
from django.contrib.auth import get_user_model

def create_superuser_final(apps, schema_editor):
    User = get_user_model()
    if not User.objects.filter(email='admin@example.com').exists():
        User.objects.create_superuser('admin@example.com', 'admin', 'admin123')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_default_superuser'),
    ]

    operations = [
        migrations.RunPython(create_superuser_final),
    ]
